server:
  port: 8083
  servlet:
    # 没有/会出错
    context-path: /springcache
spring:
#  application:
#    name: springcache
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: chenzhimei
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: chenzhimei
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springcachespringboot.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

